### ISSUE TITLE
Есть вопрос.

### ISSUE THREAD

**Issue by PomaPoma282** [PomaPoma282/HouseService#1]
@coursar
Отчаяние наступает.
Я вроде как бы по примерам сделал поиск по названию района. Как в этом поиске реализовать сортировку по цене.

**Comment by coursar** [comment]
```java
    public List<House> findAllByName(String nameDistrict) {
        List<House> result = new ArrayList<House>();

        nameDistrict = nameDistrict.toLowerCase();
        for (House house : repository.getAll()) {
            if (house.getNameDistrict().toLowerCase().contains(nameDistrict)) {
                result.add(house);
            }
        }

        result.sort(new PriceComparator()); // <--

        return result;
    }
```

@PomaPoma282, старайтесь давать issue названия по существу. Не "Есть вопрос", а "Как реализовать сортировку по цене при поиске по имени".

**Comment by coursar** [comment]
@PomaPoma282, и если задаёте вопрос - назначайте исполнителя в Asignees.
